docs_path: ./docs
root_dir: var/opt/myApp
source_to_document:
 - abs or rel path to code directory you want to parse EX- var/opt/myApp/code
requirements:
  - mkdocs: 1.4.2
  - pymdown-extensions: 9.11
ignore_folders:
 - .+\.git
 - \.pytest
 - Include
 - Lib
 - img
 - Scripts
 - docs
 - __.*__
ignore_files:
 - __.*__
 - utils.py
 - ^(?!.*\.py$).* #Only python files
use_state: True
empty_text: "# Empty File"
mkdocs:
  site_name: Auto-GPT
  site_description: The coolest thing you have seen this week
  site_url: example.com

  theme: 
    name: readthedocs

  markdown_extensions:
    - pymdownx.details
    - toc:
        permalink: true

  plugins:
    - search